<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>Рабочее место bebek</title>

    <link rel="icon" href="/version_2.0/ace_admin/assets/images/favicon/favicon.ico?v=1.0" type="image/x-icon">
    <link rel="shortcut icon" href="/version_2.0/ace_admin/assets/images/favicon/favicon.ico?v=1.0" type="image/x-icon">

    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/jquery-ui-1.11.2/jquery-ui.css">
    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/font-awesome/4.5.0/css/font-awesome.min.css" />

    <!-- page specific plugin styles -->

    <!-- text fonts -->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/fonts.googleapis.com.css" />

    <!-- ace styles -->
    <!--    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/jquery-ui.min.css" />-->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace.min.css?v=1" class="ace-main-stylesheet" id="main-ace-style" />

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace-part2.min.css" class="ace-main-stylesheet" />
    <![endif]-->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace-skins.min.css" />
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace-rtl.min.css" />

    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/chosen.min.css" />

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/ace-ie.min.css" />
    <![endif]-->

    <!-- bebek styles -->
    <link rel="stylesheet" href="/version_2.0/ace_admin/assets/css/style.css?v=1" />

    <!-- inline styles related to this page -->

    <!-- ace settings handler -->
    <script src="/version_2.0/ace_admin/assets/js/ace-extra.min.js"></script>

    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

    <!--[if lte IE 8]>
    <script src="/version_2.0/ace_admin/assets/js/html5shiv.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/respond.min.js"></script>
    <![endif]-->

    <!-------------------------------------------javascripts----------------------------------------------------->
    <!-- basic scripts -->

    <!--[if !IE]> -->
    <script src="/version_2.0/ace_admin/assets/js/jquery-2.1.4.min.js"></script>

    <!-- <![endif]-->
    
    <!--[if IE]>
    <script src="/version_2.0/ace_admin/assets/js/jquery-1.11.3.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        if('ontouchstart' in document.documentElement) document.write("<script src='/version_2.0/ace_admin/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
    </script>

<!--    <script src="/version_2.0/ace_admin/assets/js/jquery-ui.min.js"></script>-->
    <script src="/version_2.0/ace_admin/assets/jquery-ui-1.11.2/jquery-ui.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/bootstrap.min.js"></script>

    <!-- page specific plugin scripts -->

    <!-- ace scripts -->
    <script src="/version_2.0/ace_admin/assets/js/ace-elements.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/ace.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/tree.min.js"></script>
    <script src="/version_2.0/ace_admin/assets/js/chosen.jquery.min.js"></script>

    <!-- inline scripts related to this page -->

    <!-- bebek scripts -->
    <script src="/version_2.0/ace_admin/assets/js/utils.js"></script>
</head>

